### ISSUE TITLE
G4 flash latency too high

### ISSUE THREAD

**Issue by MaJerle** [MaJerle/stm32-usart-uart-dma-rx-tx#11]
https://github.com/MaJerle/stm32-usart-uart-dma-rx-tx/blob/d567cb9ae0b8f01fa8cd33f7a4c4a47f462f4681/projects/usart_rx_idle_line_irq_ringbuff_tx_loopback_G4/Src/main.c#L333

**Comment by SONGMENGSEN** [comment]
```c
static lwrb_t
usart_tx_dma_ringbuff;
```
Why is there no code like this
```c
static lwrb_t
usart_rx_dma_ringbuff;
```
feel uncomfortable
