### ISSUE TITLE
Examples for GPDMA used on STM32U575/585

### ISSUE THREAD

**Issue by gawied** [MaJerle/stm32-usart-uart-dma-rx-tx#19]

**Comment by MaJerle** [comment]
How can I help?

**Comment by gawied** [comment]
Do you any examples showing how to configure the GPDMA, as used on STM32U575/585, to do USART TX with DMA- preferably using LL_DMA and LL_UART drivers?

**Comment by MaJerle** [comment]
Added to STM32U5 branch - you can check and test if it works for you.

https://github.com/MaJerle/stm32-usart-uart-dma-rx-tx/tree/stm32u5

**Comment by gawied** [comment]
Thanks MaJerie! Will give it a try.
