### ISSUE TITLE
when dma transfer completed,is it need to reset dma memory address and datalength?

### ISSUE THREAD

**Issue by gqhyuhuofei** [MaJerle/stm32-usart-uart-dma-rx-tx#26]
when dma transfer completed,is it need to reset dma memory address and data length?
I can't find  these code given above.

**Comment by MaJerle** [comment]
If you are in circular mode, them hardware takes care of that.

**Comment by gqhyuhuofei** [comment]
> 

oh，I see it,thanks

**Comment by MaJerle** [comment]
It would be useless to have circular mode, if you have to set new values. This is then simple normal mode.

Hope it makes sense.
