### ISSUE TITLE
Opening usart_rx_polling_F4

### ISSUE THREAD

**Issue by rbeekhuijzen** [MaJerle/stm32-usart-uart-dma-rx-tx#28]
Sorry for asking this newbie question.
I've started using STM32CubeIDE/ STM32CubeMX a while ago but I would like to run your code since it is the only one with an explanation of running UART with interrupt on an RTOS.
But I have no clue as to where to start: I open the .project file and the IDE requires me to provide an .<PROJECT>.ioc file
I noticed that you're using Visual Studio instead of STM32CubeIDE and I tried to follow https://github.com/MaJerle/stm32-cube-cmake-vscode but got stuck there as well. I've installed VSudio Code and another instance of STM32CubeIDE in a seperate folder (C:\ST\STM32CubeIDE_1.10.1_VS) but whatever I click, ,nothing opens as expected.
Can you please me some pointers?

**Comment by MaJerle** [comment]
Thats not enough information - whatever I click - sorry.

**Comment by rbeekhuijzen** [comment]
In stm32cibeide i can click on the project file to open a project. Or i can
import a project
How do i open your projects from github?

**Comment by MaJerle** [comment]
You clone the repository and then go to the projects and double click to `.project` file. It will open in CubeIDE and you can compile directly.

**Comment by an518** [comment]
You clone the repository and then go to the projects and double click to .project file. It will open in CubeIDE and you can compile directly.

**Comment by rbeekhuijzen** [comment]
Ah! It works!.
I did not copy the entire zip file but only the project itself.

Could you please give me a clue on how this works?
Is there a document of some sorts that explains how the .project file
'knows' what files to copy and import the code into the STM32CubeIDE?

I normally make a project in STM32CubeIDE and set up the hardware using
STM32CubeMX and go from there.
Now I want to merge your code into a project of my own.

Sorry for this newbie question, but it feels like I'm trying to learn Latin
using a Chinese textbook (and I'm Dutch :-)
