### ISSUE TITLE
i wonder the `pos` may be handle loosely

### ISSUE THREAD

**Issue by mandy-yan** [MaJerle/stm32-usart-uart-dma-rx-tx#31]
in function `usart_rx_check`,  the variable 'position' handle made me in doubt.   why not judge the size between `position` and 'ARRAY_LEN(usart_rx_dma_buffer)'

**Comment by mandy-yan** [comment]
i see.  sorry for Interrupt

**Comment by MaJerle** [comment]
All good?

**Comment by mandy-yan** [comment]
yes. All &nbsp;Good!





------------------ Original ------------------
From: Tilen Majerle ***@***.***&gt;
Date: Tue,Jun 6,2023 1:45 PM
To: MaJerle/stm32-usart-uart-dma-rx-tx ***@***.***&gt;
Cc: Mandy.yan ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [MaJerle/stm32-usart-uart-dma-rx-tx] i wonder the `pos` may be handle loosely (Issue #31)





 
All good?
