### ISSUE TITLE
Uninitialized variable

### ISSUE THREAD

**Issue by maroviher** [MaJerle/stm32-usart-uart-dma-rx-tx#7]
in the following line
https://github.com/MaJerle/stm32-usart-uart-dma-rx-tx/blob/master/projects/usart_rx_idle_line_irq_ringbuff_G0/Src/main.c#L92
you use a not initialized variable:
static size_t old_pos;
Is it a bug?

**Comment by MaJerle** [comment]
Static variables are automatically set to zero as ler C standard.
